name: npm build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Build npm release
        run: |
          deno run -A build_npm.ts "$(deno eval 'import { VERSION } from "./version.ts"; console.log(VERSION);')"
